# Generated by Django 4.2.2 on 2023-07-20 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consecionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nombreGerente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaM', models.CharField(max_length=30)),
                ('añoFabM', models.IntegerField()),
                ('valorFijo', models.FloatField()),
                ('tipo', models.CharField(choices=[('trabajo', 'Trabajo'), ('deportiva', 'Deportiva')], max_length=30)),
                ('consecionaria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motosC', to='TEC.consecionaria')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('añoFab', models.IntegerField()),
                ('costoMin', models.FloatField()),
                ('costoMax', models.FloatField()),
                ('color', models.CharField(max_length=30)),
                ('valorSeguro', models.FloatField()),
                ('consecionaria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosC', to='TEC.consecionaria')),
            ],
        ),
    ]
