# Generated by Django 4.2.2 on 2023-07-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('expositor', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('metodologia', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('publico', models.CharField(max_length=100)),
                ('reporte', models.CharField(max_length=100)),
            ],
        ),
    ]
