# Generated by Django 4.2.2 on 2023-07-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEC', '0002_controle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpositoresCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('conocimientos', models.CharField(max_length=100)),
                ('numEventos', models.CharField(max_length=100)),
                ('calificacion', models.CharField(max_length=100)),
                ('presupuesto', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
