# Generated by Django 4.2.3 on 2023-08-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEC', '0003_expositorescon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
    ]
