# Generated by Django 4.2.3 on 2023-08-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEC', '0004_ponentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponentes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
